# Machine Learning Zoomcamp

## 1.7 Introduction to NumPy

Plan:
- Creating arrays
- Multi-dimentional array
- Randomly generated arrays
- Element-wise operations
    - Comparison operations
    - Logical operations
- Summarizing operations

In [5]:
import numpy as np

In [6]:
np

<module 'numpy' from '/home/don/miniconda3/lib/python3.8/site-packages/numpy/__init__.py'>

## Creating arrays

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [16]:
a[2]

3

In [17]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [27]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [35]:
n[0, 1] = 20

In [36]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
n[0]

array([ 1, 20,  3])

In [38]:
n[1]

array([4, 5, 6])

In [40]:
n[2] = [1, 1, 1]

In [42]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [43]:
n[:, 1]

array([20,  5,  1])

In [44]:
n[:, 2]

array([3, 6, 1])

In [45]:
n[:, 2] = [0, 1, 2]

In [46]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [47]:
np.random.rand(5, 2)

array([[0.231976  , 0.74911649],
       [0.8326009 , 0.13289997],
       [0.27142672, 0.41198653],
       [0.97242509, 0.03984149],
       [0.92495703, 0.96274713]])

In [48]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [49]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [51]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [52]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [55]:
a + 1

array([1, 2, 3, 4, 5])

In [56]:
a * 2

array([0, 2, 4, 6, 8])

In [57]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [58]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [60]:
b = (10 + (a * 2)) ** 2 / 100

In [61]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [62]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [63]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [64]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [65]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison opertaions

In [66]:
a

array([0, 1, 2, 3, 4])

In [67]:
a >= 2

array([False, False,  True,  True,  True])

In [68]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [69]:
a > b

array([False, False,  True,  True,  True])

In [70]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [73]:
a

array([0, 1, 2, 3, 4])

In [72]:
a.min()

0

In [74]:
a.sum()

10

In [75]:
a.max()

4

In [76]:
a.mean()

2.0

In [77]:
a.std()

1.4142135623730951

In [78]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [79]:
n.min()

0

In [80]:
n.sum()

35

In [82]:
n.sum([:, 2])

SyntaxError: invalid syntax (3717925216.py, line 1)

In [85]:
sum(n[:, 1])

26